version: "3.9"

services:

  # postgres:
  #   image: postgres:15
  #   container_name: gym_postgres
  #   restart: unless-stopped

  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: postgres
  #     POSTGRES_DB: gym_activity

  #   ports:
  #     - "5433:5432"   # хост → контейнер

  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  bot:
    build: .
    container_name: app
    restart: always
    env_file:
      - .env
    volumes:
      - .:/app
    command: python bot.py


# volumes:
#   postgres_data: